version: "3.4"
services:
  mongodb:
    image : mongo
    container_name: "mongodb"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

  api-dev:
    image: node
    container_name: "api-dev"
    working_dir: /code
    volumes:
      - .:/code:delegated
    ports:
      - 4000:4000
    command: bash -c "npm install && npm run dev"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./src/app/docs/:/app
    environment:
      SWAGGER_JSON: /app/spec.yaml